# Generated by Django 6.0 on 2025-12-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
